# Generated by Django 5.2 on 2025-05-05 16:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deces',
            fields=[
                ('pk', models.CompositePrimaryKey('date_deces', 'lieu_deces', 'acte_deces', blank=True, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, max_length=100, null=True)),
                ('prenoms', models.CharField(blank=True, max_length=200, null=True)),
                ('sexe', models.CharField(max_length=1)),
                ('date_naissance', models.DateField()),
                ('lieu_naissance', models.CharField(max_length=5)),
                ('commune_naissance', models.CharField(max_length=100)),
                ('pays_naissance', models.CharField(blank=True, max_length=100)),
                ('date_deces', models.DateField()),
                ('lieu_deces', models.CharField(max_length=100)),
                ('acte_deces', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Décès',
                'verbose_name_plural': 'Décès',
                'indexes': [models.Index(fields=['nom'], name='deces_deces_nom_ef37bb_idx'), models.Index(fields=['prenoms'], name='deces_deces_prenoms_4bc154_idx'), models.Index(fields=['sexe'], name='deces_deces_sexe_bb3a1c_idx'), models.Index(fields=['date_naissance'], name='deces_deces_date_na_89f42d_idx'), models.Index(fields=['lieu_naissance'], name='deces_deces_lieu_na_8ab466_idx'), models.Index(fields=['date_deces'], name='deces_deces_date_de_eefd85_idx'), models.Index(fields=['lieu_deces'], name='deces_deces_lieu_de_8a0327_idx')],
            },
        ),
        migrations.CreateModel(
            name='ImportHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_url', models.URLField(max_length=500)),
                ('zip_filename', models.CharField(default='unknown.zip', max_length=255)),
                ('csv_filename', models.CharField(max_length=255)),
                ('md5_hash', models.CharField(help_text='MD5 hash du fichier CSV', max_length=32)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('downloading', 'Téléchargement'), ('checking', 'Vérification'), ('processing', 'En cours'), ('completed', 'Terminé'), ('failed', 'Échec')], default='pending', max_length=20)),
                ('records_processed', models.IntegerField(default=0)),
                ('total_records', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': "Historique d'import",
                'verbose_name_plural': "Historiques d'imports",
                'ordering': ['-started_at'],
                'unique_together': {('csv_filename', 'md5_hash')},
            },
        ),
    ]
