# Generated by Django 5.2 on 2025-05-02 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenoms', models.CharField(max_length=200)),
                ('sexe', models.CharField(max_length=1)),
                ('date_naissance', models.DateField()),
                ('lieu_naissance', models.CharField(max_length=5)),
                ('commune_naissance', models.CharField(max_length=100)),
                ('pays_naissance', models.CharField(blank=True, max_length=100)),
                ('date_deces', models.DateField()),
                ('lieu_deces', models.CharField(max_length=5)),
                ('acte_deces', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Décès',
                'verbose_name_plural': 'Décès',
                'indexes': [models.Index(fields=['nom'], name='deces_deces_nom_ef37bb_idx'), models.Index(fields=['prenoms'], name='deces_deces_prenoms_4bc154_idx'), models.Index(fields=['date_naissance'], name='deces_deces_date_na_89f42d_idx'), models.Index(fields=['date_deces'], name='deces_deces_date_de_eefd85_idx')],
            },
        ),
    ]
