# Generated by Django 5.2 on 2025-05-02 09:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('filename', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('completed', 'Terminé'), ('failed', 'Échec')], default='pending', max_length=20)),
                ('records_processed', models.IntegerField(default=0)),
                ('total_records', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('md5_hash', models.CharField(max_length=32, unique=True)),
            ],
            options={
                'verbose_name': "Historique d'import",
                'verbose_name_plural': "Historiques d'imports",
                'ordering': ['-started_at'],
            },
        ),
    ]
