# Generated by Django 5.2 on 2025-05-02 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deces', '0002_importhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='importhistory',
            name='current_file',
            field=models.CharField(blank=True, help_text='Nom du fichier CSV en cours de traitement', max_length=255),
        ),
    ]
