# Generated by Django 5.2 on 2025-05-02 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deces', '0003_importhistory_current_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deces',
            name='lieu_deces',
            field=models.CharField(max_length=100),
        ),
    ]
