# Generated by Django 5.2 on 2025-05-13 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deces', '0004_deces_lieu_naissance_nom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deces',
            name='date_naissance',
            field=models.DateField(null=True),
        ),
    ]
