# Generated by Django 5.2 on 2025-05-02 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deces', '0004_alter_deces_lieu_deces'),
    ]

    operations = [
        migrations.RenameField(
            model_name='importhistory',
            old_name='filename',
            new_name='csv_filename',
        ),
        migrations.RenameField(
            model_name='importhistory',
            old_name='url',
            new_name='zip_url',
        ),
        migrations.AlterUniqueTogether(
            name='importhistory',
            unique_together={('csv_filename', 'md5_hash')},
        ),
        migrations.AddField(
            model_name='importhistory',
            name='zip_filename',
            field=models.CharField(default='unknown.zip', max_length=255),
        ),
        migrations.AlterField(
            model_name='importhistory',
            name='md5_hash',
            field=models.CharField(help_text='MD5 hash du fichier CSV', max_length=32),
        ),
        migrations.RemoveField(
            model_name='importhistory',
            name='current_file',
        ),
    ]
