# Generated by Django 5.2 on 2025-05-14 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deces', '0005_alter_deces_date_naissance'),
    ]

    operations = [
        migrations.CreateModel(
            name='DecesImportError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_data', models.JSONField(help_text='Données brutes de la ligne en erreur')),
                ('error_message', models.TextField(help_text="Message d'erreur lors de l'import")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('resolution_date', models.DateTimeField(blank=True, null=True)),
                ('nom', models.CharField(blank=True, max_length=100, null=True)),
                ('prenoms', models.CharField(blank=True, max_length=200, null=True)),
                ('sexe', models.CharField(blank=True, max_length=1, null=True)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('lieu_naissance', models.CharField(blank=True, max_length=5, null=True)),
                ('lieu_naissance_nom', models.CharField(blank=True, max_length=200, null=True)),
                ('date_deces', models.DateField(blank=True, null=True)),
                ('lieu_deces', models.CharField(blank=True, max_length=5, null=True)),
                ('acte_deces', models.CharField(blank=True, max_length=10, null=True)),
                ('import_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='deces.importhistory')),
            ],
            options={
                'verbose_name': "Erreur d'import",
                'verbose_name_plural': "Erreurs d'import",
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['resolved'], name='deces_deces_resolve_73769d_idx'), models.Index(fields=['import_history'], name='deces_deces_import__e9c342_idx')],
            },
        ),
    ]
