# Generated by Django 5.2 on 2025-05-03 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deces', '0005_rename_filename_importhistory_csv_filename_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deces',
            name='nom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='deces',
            name='prenoms',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
