# Generated by Django 5.2 on 2025-05-14 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deces', '0006_decesimporterror'),
    ]

    operations = [
        migrations.AddField(
            model_name='decesimporterror',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='decesimporterror',
            name='import_history',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deces.importhistory'),
        ),
    ]
