# Generated by Django 5.2 on 2025-05-04 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deces', '0006_alter_deces_nom_alter_deces_prenoms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importhistory',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('downloading', 'Téléchargement'), ('checking', 'Vérification'), ('processing', 'En cours'), ('completed', 'Terminé'), ('failed', 'Échec')], default='pending', max_length=20),
        ),
    ]
